
DBHA_BASE=/cloud/dahua/DataBaseServer/DBHA
DBHA_LOG=$DBHA_BASE/Log
DBHA_SHELL=$DBHA_BASE/Shell
DBHA_BIN=$DBHA_BASE/Bin
DBHA_CONFIG=$DBHA_BASE/Config
#EFS_NEW_INSTALL_FILE=/cloud/dahua/EFS/newinstall
#EFS_MDS_NEW_INSTALL_FILE=/cloud/dahua/EFS/mdsnewinstall
#EFS_MDS_NEW_EXPAND_FILE=/cloud/dahua/EFS/mdsnewexpand

export DBHA_BASE=$DBHA_BASE
export DBHA_LOG=$DBHA_LOG
export DBHA_SHELL=$DBHA_SHELL
export DBHA_BIN=$DBHA_BIN
export DBHA_CONFIG=$DBHA_CONFIG

#export EFS_NEW_INSTALL_FILE=$EFS_NEW_INSTALL_FILE
#export EFS_MDS_NEW_INSTALL_FILE=$EFS_MDS_NEW_INSTALL_FILE
#export EFS_MDS_NEW_EXPAND_FILE=$EFS_MDS_NEW_EXPAND_FILE
